# Generated by Django 3.2 on 2025-06-26 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra', models.JSONField(default=dict)),
                ('type', models.TextField(choices=[('Integration A', 'Integration A'), ('Integration B', 'Integration B')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onetable_with_pydantic.baseintegration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationA',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onetable_with_pydantic.baseintegration',),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationB',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onetable_with_pydantic.baseintegration',),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
    ]
