# Generated by Django 3.2 on 2025-06-26 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationA',
            fields=[
                ('baseintegration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitable.baseintegration')),
                ('custom_prop_a', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Integration A',
                'verbose_name_plural': 'Integrations A',
            },
            bases=('multitable.baseintegration',),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationB',
            fields=[
                ('baseintegration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitable.baseintegration')),
                ('custom_prop_b', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Integration B',
                'verbose_name_plural': 'Integrations B',
            },
            bases=('multitable.baseintegration',),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitable.baseintegration')),
            ],
        ),
    ]
